name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    permissions:
      contents: read
      id-token: write
    uses: harryzcy/github-actions/.github/workflows/go.yml@main
